name: same_test
on: [push]

jobs:
  io_test:
    name: Use Linux commands
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Permission Setting
        run: chmod +x samew.sh test_same2.sh
      - name: Test Run
        run: ./test_same2.sh
